"""empty message

Revision ID: 766fd53fa124
Revises: 8e8a869889b8
Create Date: 2019-11-20 12:05:19.965288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766fd53fa124'
down_revision = '8e8a869889b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'column_for_migration_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('column_for_migration_test', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
