version: "3.3"
services:
  pockemon:
    build: .
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/status/ | grep OK"]
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
